export const DIALOG_SET = 'DIALOG_SET';
export const DIALOG_REMOVE = 'DIALOG_REMOVE';

export const ENQUEUE_SNACKBAR = `ENQUEUE_SNACKBAR`;
export const REMOVE_SNACKBAR = `REMOVE_SNACKBAR`;
export const CLOSE_SNACKBAR = `CLOSE_SNACKBAR`;
